In [0]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers.normalization import BatchNormalization
from keras import metrics
from keras.callbacks import ModelCheckpoint

from imblearn.over_sampling import SMOTE

from pathlib import Path

from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
import matplotlib.pyplot as plt
import math
import time

from sklearn.metrics import classification_report

from  scipy import ndimage, fft
from sklearn.preprocessing import normalize

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)

In [0]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers.normalization import BatchNormalization
from keras import metrics
from keras.callbacks import ModelCheckpoint

from imblearn.over_sampling import SMOTE

from pathlib import Path

from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
import matplotlib.pyplot as plt
import math
import time

from sklearn.metrics import classification_report

from  scipy import ndimage, fft
from sklearn.preprocessing import normalize

#from preprocess_data import LightFluxProcessor

np.random.seed(42)

LOAD_MODEL = True # continue training previous weights or start fresh
RENDER_PLOT = False # render loss and accuracy plots

def build_network():
      # Model config
      learning_rate = 0.001

      layers = [
          { "units": 1000, "input_dim": n_x, "activation": 'relu', "dropout": 0 },
          { "units": n_y, "input_dim": 1, "activation": 'sigmoid', "dropout": 0 },
      ]

      # Build model
      model = Sequential()
      model.add(Dense(1000, input_dim=n_x, activation='relu'))
      #model.add(Dense(500, activation='relu'))
      model.add(Dense(10, activation='relu'))
      model.add(Dense(1, activation='sigmoid'))

      model.compile(loss=keras.losses.binary_crossentropy,
                    optimizer=keras.optimizers.Adam(lr=learning_rate),
                    metrics=['accuracy'])
      return model

def np_X_Y_from_df(df):
      df = shuffle(df)
      df_X = df.drop(['tfopwg_disp'], axis=1)
      X = np.array(df_X)
      Y_raw = np.array(df['tfopwg_disp']).reshape((len(df['tfopwg_disp']),1))
      Y = Y_raw == 1
      return X, Y
    
if __name__ == "__main__":

      print("Loading datasets...")
      df_train = train
      df_dev = val

      # Generate X and Y dataframe sets
      df_train_x = df_train.drop(['tid','tfopwg_disp'], axis=1)
      df_dev_x = df_dev.drop(['tid','tfopwg_disp'], axis=1)
      df_train_y = df_train.tfopwg_disp
      df_dev_y = df_dev.tfopwg_disp

      # Process dataset
      LFP = LightFluxProcessor(
          fourier=False,
          normalize=True,
          gaussian=True,
          standardize=True)
      df_train_x, df_dev_x = LFP.process(df_train_x, df_dev_x)

      # Rejoin X and Y
      df_train_processed = pd.DataFrame(df_train_x).join(pd.DataFrame(df_train_y))
      df_dev_processed = pd.DataFrame(df_dev_x).join(pd.DataFrame(df_dev_y.reset_index().drop(['index'],axis=1)))

      # Load X and Y numpy arrays
      X_train, Y_train = np_X_Y_from_df(df_train_processed)
      X_dev, Y_dev = np_X_Y_from_df(df_dev_processed)

      # Print data set stats
      (num_examples, n_x) = X_train.shape # (n_x: input size, m : number of examples in the train set)
      n_y = Y_train.shape[1] # n_y : output size
      print("X_train.shape: ", X_train.shape)
      print("Y_train.shape: ", Y_train.shape)
      print("X_dev.shape: ", X_dev.shape)
      print("Y_dev.shape: ", Y_dev.shape)
      print("n_x: ", n_x)
      print("num_examples: ", num_examples)
      print("n_y: ", n_y)

      # Build model
      model = build_network()

      # Load weights
      load_path=""
      my_file = Path(load_path)
      if LOAD_MODEL and my_file.is_file():
          model.load_weights(load_path)
          print("------------")
          print("Loaded saved weights")
          print("------------")


      #sm = SMOTE(ratio = 1.0)
     # X_train_sm, Y_train_sm = sm.fit_sample(X_train, Y_train)
      # X_train_sm, Y_train_sm = X_train, Y_train


      # Train
      # checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
      # callbacks_list = [checkpoint]
      print("Training...")
      history = model.fit(X_train, Y_train, epochs=20, batch_size=16)

      # Metrics
      train_outputs = model.predict(X_train)
      dev_outputs = model.predict(X_dev)
      train_outputs = np.rint(train_outputs)
      dev_outputs = np.rint(dev_outputs)
      accuracy_train = accuracy_score(Y_train, train_outputs)
      accuracy_dev = accuracy_score(Y_dev, dev_outputs)
      precision_train = precision_score(Y_train, train_outputs)
      precision_dev = precision_score(Y_dev, dev_outputs)
      recall_train = recall_score(Y_train, train_outputs)
      recall_dev = recall_score(Y_dev, dev_outputs)
      confusion_matrix_train = confusion_matrix(Y_train, train_outputs)
      confusion_matrix_dev = confusion_matrix(Y_dev, dev_outputs)

NameError: ignored

In [0]:
test = pd.read_csv('https://raw.githubusercontent.com/BW-Finding-Planets/Machinelearning/master/fluxes_no_duplicates.csv')

In [0]:
test = test.iloc[:,2:]

In [0]:
test.head()

               0              1              2  ...  19579  19580      ticid
0   27241.781250   27278.267578   27265.912109  ...    NaN    NaN  278683844
1   11893.570312   11897.396484   11903.706055  ...    NaN    NaN  391949880
2  104079.234375  104005.265625  104032.492188  ...    NaN    NaN  263003176
3  159893.375000  159939.390625  159891.671875  ...    NaN    NaN   89020549
4    6609.128906    6604.856934    6594.187012  ...    NaN    NaN   62483237

[5 rows x 19582 columns]

In [0]:
def reduce_df(df,n=3197):
    temp_df = df.iloc[:,0]
    #n = df.shape[1]//test_flux.shape[1]
    for i in range(1,df.shape[1],5):
        temp_df2 = df.iloc[:,i]
        temp_df = pd.concat([temp_df,temp_df2], axis=1)
    return temp_df

In [0]:
ID = test.ticid

In [0]:
test = test.drop(['ticid'],axis=1)

In [0]:
test = reduce_df(test.iloc[:,:16327])

In [0]:
test = test.fillna(0)

In [0]:
import pandas as pd
import numpy as np
from scipy import ndimage, fft
from sklearn.preprocessing import normalize, StandardScaler, MinMaxScaler

class LightFluxProcessor:

    def __init__(self, fourier=True, normalize=True, gaussian=True, standardize=True):
        self.fourier = fourier
        self.normalize = normalize
        self.gaussian = gaussian
        self.standardize = standardize

    def fourier_transform(self, X):
        return np.abs(fft(X, n=X.size))

    def process(self, df_train_x, df_dev_x):
        # Generate X and Y sets
        # df_train_x = df_train.drop('LABEL', axis=1)
        # df_dev_x = df_dev.drop('LABEL', axis=1)
        # df_train_y = df_train.LABEL
        # df_dev_y = df_dev.LABEL

        # Apply fourier transform
        if self.fourier:
            print("Applying Fourier...")
            df_train_x = df_train_x.apply(self.fourier_transform,axis=0)
            df_dev_x = df_dev_x.apply(self.fourier_transform,axis=0)

            # Keep first half of data as it is symmetrical after previous steps
            df_train_x = df_train_x.iloc[:,:(df_train_x.shape[1]//2)].values
            df_dev_x = df_dev_x.iloc[:,:(df_dev_x.shape[1]//2)].values
            
        if self.normalize:
            print("Normalizing...")
            df_train_x = pd.DataFrame(normalize(df_train_x))
            df_dev_x = pd.DataFrame(normalize(df_dev_x))



        # Gaussian filter to smooth out data
        if self.gaussian:
            print("Applying Gaussian Filter...")
            df_train_x = ndimage.filters.gaussian_filter(df_train_x, sigma=10)
            df_dev_x = ndimage.filters.gaussian_filter(df_dev_x, sigma=10)

        if self.standardize:
            # Standardize X data
            print("Standardizing...")
            std_scaler = StandardScaler()
            df_train_x = std_scaler.fit_transform(df_train_x)
            df_dev_x = std_scaler.transform(df_dev_x)
                # Normalize

           

        print("Finished Processing!")
        return df_train_x, df_dev_x

In [0]:
# Process dataset
LFP = LightFluxProcessor(
    fourier=False,
    normalize=True,
    gaussian=True,
    standardize=True)
test, test2 = LFP.process(test, test)

Normalizing...
Applying Gaussian Filter...
Standardizing...
Finished Processing!

In [0]:
def build_network():
      # Model config
      learning_rate = 0.001

      layers = [
          { "units": 1000, "input_dim": test.shape[1], "activation": 'relu', "dropout": 0 },
          { "units": 1, "input_dim": 1, "activation": 'sigmoid', "dropout": 0 },
      ]

      # Build model
      model = Sequential()
      model.add(Dense(1000, input_dim=(test.shape[1]), activation='relu'))
      model.add(Dense(500, activation='relu'))
      model.add(Dense(200, activation='relu'))
      model.add(Dense(1, activation='sigmoid'))

      model.compile(loss=keras.losses.binary_crossentropy,
                    optimizer=keras.optimizers.Adam(lr=learning_rate),
                    metrics=['accuracy'])
      return model

In [0]:
model = build_network()

In [0]:
LOAD_MODEL=True
if __name__ == "__main__":
      load_path="/content/model3"
      my_file = Path(load_path)
      if LOAD_MODEL and my_file.is_file():
        model.load_weights(load_path)
        print("------------")
        print("Loaded saved weights")
        print("------------")


      #sm = SMOTE(ratio = 1.0)
      # X_train_sm, Y_train_sm = sm.fit_sample(X_train, Y_train)
      # X_train_sm, Y_train_sm = X_train, Y_train


      # Train
      # checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
      # callbacks_list = [checkpoint]

------------
Loaded saved weights
------------

In [0]:
model.predict(test)

array([[6.7671096e-01],
       [6.7845535e-01],
       [6.8190014e-01],
       [6.8703693e-01],
       [6.9341165e-01],
       [7.0022070e-01],
       [7.0788717e-01],
       [7.1554798e-01],
       [7.2238797e-01],
       [7.2816676e-01],
       [7.3222101e-01],
       [7.3475999e-01],
       [7.3533684e-01],
       [7.3244989e-01],
       [7.2728390e-01],
       [7.1939927e-01],
       [7.0910352e-01],
       [6.9612586e-01],
       [6.8070048e-01],
       [6.6414958e-01],
       [6.4672530e-01],
       [6.3687181e-01],
       [6.3792217e-01],
       [6.0008705e-01],
       [3.5847184e-01],
       [2.6558310e-02],
       [1.4036894e-05],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00]], dtype=float32)

In [0]:
predictions3 =  model.predict(test)

In [0]:
pd.DataFrame(predictions3)

           0
0   0.676711
1   0.678455
2   0.681900
3   0.687037
4   0.693412
5   0.700221
6   0.707887
7   0.715548
8   0.722388
9   0.728167
10  0.732221
11  0.734760
12  0.735337
13  0.732450
14  0.727284
15  0.719399
16  0.709104
17  0.696126
18  0.680700
19  0.664150
20  0.646725
21  0.636872
22  0.637922
23  0.600087
24  0.358472
25  0.026558
26  0.000014
27  0.000000
28  0.000000
29  0.000000
30  0.000000
31  0.000000
32  0.000000
33  0.000000
34  0.000000
35  0.000000
36  0.000000
37  0.000000
38  0.000000
39  0.000000
40  0.000000
41  0.000000
42  0.000000
43  0.000000
44  0.000000
45  0.000000
46  0.000000
47  0.000000
48  0.000000
49  0.000000
50  0.000000
51  0.000000
52  0.000000
53  0.000000

In [0]:
pd.DataFrame(predictions2)

           0
0   0.676711
1   0.678455
2   0.681900
3   0.687037
4   0.693412
5   0.700221
6   0.707887
7   0.715548
8   0.722388
9   0.728167
10  0.732221
11  0.734760
12  0.735337
13  0.732450
14  0.727284
15  0.719399
16  0.709104
17  0.696126
18  0.680700
19  0.664150
20  0.646725
21  0.636872
22  0.637922
23  0.600087
24  0.358472
25  0.026558
26  0.000014
27  0.000000
28  0.000000
29  0.000000
30  0.000000
31  0.000000
32  0.000000
33  0.000000
34  0.000000
35  0.000000
36  0.000000
37  0.000000
38  0.000000
39  0.000000
40  0.000000
41  0.000000
42  0.000000
43  0.000000
44  0.000000
45  0.000000
46  0.000000
47  0.000000
48  0.000000
49  0.000000
50  0.000000
51  0.000000
52  0.000000
53  0.000000

In [0]:
predictions

array([[0.05104509],
       [0.0514203 ],
       [0.05224562],
       [0.05349052],
       [0.05457571],
       [0.05609486],
       [0.05811006],
       [0.06029999],
       [0.06250948],
       [0.06564459],
       [0.07250682],
       [0.08121851],
       [0.09087783],
       [0.10491085],
       [0.12366953],
       [0.14768621],
       [0.18116757],
       [0.22373635],
       [0.26108158],
       [0.29688197],
       [0.32874072],
       [0.36706182],
       [0.4084137 ],
       [0.4209037 ],
       [0.41158342],
       [0.4305062 ],
       [0.4477529 ],
       [0.4515448 ],
       [0.44791722],
       [0.44843325],
       [0.447985  ],
       [0.4471581 ],
       [0.44987   ],
       [0.45324713],
       [0.4574607 ],
       [0.46053833],
       [0.46336356],
       [0.46615857],
       [0.4688533 ],
       [0.47161803],
       [0.4746249 ],
       [0.4772818 ],
       [0.47948664],
       [0.47743106],
       [0.47426003],
       [0.4711597 ],
       [0.46777186],
       [0.46415558],
       [0.46034282],
       [0.45712528],
       [0.4544121 ],
       [0.45087343],
       [0.44833663],
       [0.44702995]], dtype=float32)

In [0]:
prediction_df = pd.DataFrame(predictions2, columns=['predictions'])

In [0]:
prediction_df

    predictions
0      0.676711
1      0.678455
2      0.681900
3      0.687037
4      0.693412
5      0.700221
6      0.707887
7      0.715548
8      0.722388
9      0.728167
10     0.732221
11     0.734760
12     0.735337
13     0.732450
14     0.727284
15     0.719399
16     0.709104
17     0.696126
18     0.680700
19     0.664150
20     0.646725
21     0.636872
22     0.637922
23     0.600087
24     0.358472
25     0.026558
26     0.000014
27     0.000000
28     0.000000
29     0.000000
30     0.000000
31     0.000000
32     0.000000
33     0.000000
34     0.000000
35     0.000000
36     0.000000
37     0.000000
38     0.000000
39     0.000000
40     0.000000
41     0.000000
42     0.000000
43     0.000000
44     0.000000
45     0.000000
46     0.000000
47     0.000000
48     0.000000
49     0.000000
50     0.000000
51     0.000000
52     0.000000
53     0.000000

In [0]:
prediction_df = prediction_df.merge(ID,how='left', left_index=True,right_index=True)

In [0]:
prediction_df

    predictions      ticid
0      0.676711  278683844
1      0.678455  391949880
2      0.681900  263003176
3      0.687037   89020549
4      0.693412   62483237
5      0.700221  140068425
6      0.707887  425934411
7      0.715548  260985861
8      0.722388  271893367
9      0.728167  140691463
10     0.732221  394657039
11     0.734760  348770361
12     0.735337  179317684
13     0.732450  149990841
14     0.727284  183120439
15     0.719399  394698182
16     0.709104  309257814
17     0.696126  425997655
18     0.680700  262530407
19     0.664150   76923707
20     0.646725  183979262
21     0.636872  183985250
22     0.637922   12421862
23     0.600087  309792357
24     0.358472  350618622
25     0.026558  355509914
26     0.000014  259962054
27     0.000000  281781375
28     0.000000  281575427
29     0.000000   55650590
30     0.000000  314865962
31     0.000000   52204645
32     0.000000  141608198
33     0.000000  167415965
34     0.000000   32090583
35     0.000000  150098860
36     0.000000  316937670
37     0.000000  144440290
38     0.000000  326453034
39     0.000000   70797900
40     0.000000   47525799
41     0.000000    2760710
42     0.000000  160074939
43     0.000000  415969908
44     0.000000   12423815
45     0.000000  280095254
46     0.000000  305048087
47     0.000000    9006668
48     0.000000  101948569
49     0.000000  118327550
50     0.000000  154618248
51     0.000000  179985715
52     0.000000  322063810
53     0.000000   49687222

In [0]:
prediction_df.to_csv(r'predictions.csv')

In [0]:
data = pd.read_csv('https://raw.githubusercontent.com/BW-Finding-Planets/Machinelearning/master/new_data.csv')

In [0]:
data = data.merge(prediction_df, how='left', left_index=True,right_index=True)

In [0]:
data = data.drop(['ticid_y','Unnamed: 0'],axis=1)

In [0]:
data.shape

(54, 12)

In [0]:
data.to_csv(r'final data with predictions.csv')

In [0]:
      print("Training...")
      history = model.fit(X_train, Y_train, epochs=20, batch_size=16)

      # Metrics
      train_outputs = model.predict(X_train)
      dev_outputs = model.predict(X_dev)
      train_outputs = np.rint(train_outputs)
      dev_outputs = np.rint(dev_outputs)
      accuracy_train = accuracy_score(Y_train, train_outputs)
      accuracy_dev = accuracy_score(Y_dev, dev_outputs)
      precision_train = precision_score(Y_train, train_outputs)
      precision_dev = precision_score(Y_dev, dev_outputs)
      recall_train = recall_score(Y_train, train_outputs)
      recall_dev = recall_score(Y_dev, dev_outputs)
      confusion_matrix_train = confusion_matrix(Y_train, train_outputs)
      confusion_matrix_dev = confusion_matrix(Y_dev, dev_outputs)